function sum complete
js-tasks-ru/jsbasic-20220211_londort pull request #1
Opened 2022-02-11 16:28 UTC by Londort

я не совсем понял для чего была нужна вторая строчка в условии. npm test выдавал мне верный ответ лишь при сложении первой.

2022-02-11 18:34 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-02-11 18:34 UTC, SinimaWath requested changes

2022-02-11 18:34 UTC, SinimaWath commented on 0-module/1-task/index.js
> +  return 1 + 1;
Твоя функция не будет работать, если вызывать ее так: `sum(3, 4)`;

Надо использовать аргументы: `return m + n`

2022-02-13 15:49 UTC, SinimaWath approved these changes

2022-02-13 15:49 UTC, merged