UpperCase first symbol and an empty line
js-tasks-ru/jsbasic-20220211_londort pull request #3
Opened 2022-02-16 18:29 UTC by Londort

Я не совсем понял как избежать пробелов в самом слове, в случае, если, вдруг, пользователь, нечаянно, нажмёт пробел внутри "вани". 
пробовал разные варианты, но, вероятно, мы это будем проходить позже. На этом этапе я не понял как это сделать.

2022-02-16 18:30 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-02-16 18:34 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-02-17 09:33 UTC, SinimaWath requested changes

2022-02-17 09:33 UTC, SinimaWath commented on 1-module/3-task/index.js
> +  if (str == false) {
это немного не логичная проверка:
Правильно будет так, как показывал на лекции:
```
if (!str) {
  return str
}
```

2022-02-17 09:33 UTC, SinimaWath commented on 1-module/3-task/index.js
> +  let trimmer = str.trim();
В задаче, можно без trim

2022-02-17 11:53 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-02-18 09:30 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-02-18 09:48 UTC, SinimaWath approved these changes
все ок

2022-02-18 09:49 UTC, merged